spring:
  application:
    name: my-spring-boot
  datasource:
    druid:
      db-type: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false
      username: root
      password: 123456
      initial-size: 10
      maxActive: 100
      minIdle: 10
      maxWait: 6000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

